/**
 * Cocos Creator Shader Techniques 模板
 */

/**
 * 生成完整的 CCEffect 區塊
 */
export function generateCCEffect(properties: string): string {
  return `// Generated by FBX Optimizer - Cocos Creator Shader Export
// Copyright (c) 2017-2020 Xiamen Yaji Software Co., Ltd.
CCEffect %{
  techniques:
  - name: opaque
    passes:
    - vert: custom-vs:vert
      frag: custom-fs:frag
      properties: &props
${properties}
      migrations: &migs
        properties:
          mainColor:    { formerlySerializedAs: color }
  - name: transparent
    passes:
    - vert: custom-vs:vert
      frag: custom-fs:frag
      depthStencilState:
        depthTest: true
        depthWrite: false
      blendState:
        targets:
        - blend: true
          blendSrc: src_alpha
          blendDst: one_minus_src_alpha
          blendDstAlpha: one_minus_src_alpha
      properties: *props
      migrations: *migs
  - name: add
    passes:
    - vert: custom-vs:vert
      frag: custom-fs:frag
      rasterizerState: &r1 { cullMode: none }
      depthStencilState: &d1
        depthTest: true
        depthWrite: false
      blendState:
        targets:
        - blend: true
          blendSrc: src_alpha
          blendDst: one
          blendSrcAlpha: src_alpha
          blendDstAlpha: one
      properties: *props
      migrations: *migs
}%`;
}

/**
 * 生成 Vertex Shader CCProgram 區塊
 */
export function generateVertexProgram(
  includes: string,
  declarations: string,
  mainFunction: string
): string {
  return `

CCProgram custom-vs %{
${includes}
${declarations}
${mainFunction}
}%`;
}

/**
 * 生成 Fragment Shader CCProgram 區塊
 */
export function generateFragmentProgram(
  includes: string,
  declarations: string,
  mainFunction: string
): string {
  return `

CCProgram custom-fs %{
${includes}
${declarations}
${mainFunction}
}%`;
}

